apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: mailjky/multi-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
        env:
         - name: REDIS_HOST
           value: redis-cluster-ip-service
         - name: REDIS_PORT
           value: "6379"
         - name: PGHOST
           value: postgresss-cluster-ip-service
         - name: PGDATABASE
           value: postgres
         - name: PGUSER
           value: postgres
         - name: PGPORT
           value: "5432"
         - name: PGPASSWORD
           valueFrom:
            secretKeyRef:
              name: pgpassword
              key: PGPASSWORD
